### ISSUE TITLE
Release planned ?

### ISSUE THREAD

**Issue by jonesbusy** [tofuutils/pre-commit-opentofu#2]
Hi,

Thanks for this repo, works like a charm after migration from terraform to opentofu.

Is there a release planned instead of depending on the 'main' branch ?

```
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: main # I would like a tag here
    hooks:
      - id: tofu_fmt
      - id: tofu_tflint
```

Thanks
