### ISSUE TITLE
Error "multiple targets cannot be specified" using tofu_trivy hook in Github Action

### ISSUE THREAD

**Issue by figaw** [tofuutils/pre-commit-opentofu#9]
### Describe the bug

We get the following error in our Github Action:

```log
Run pre-commit run --show-diff-on-failure --color=always --all-files

[INFO] Initializing environment for https://github.com/tofuutils/pre-commit-opentofu.
OpenTofu validate with trivy.............................................Failed
- hook id: tofu_trivy
- exit code: 1
2024-09-18T11:40:02.154Z	ERROR	multiple targets cannot be specified
2024-09-18T11:40:02.154Z	FATAL	option initialize error: arguments error
2024-09-18T11:40:02.169Z	ERROR	multiple targets cannot be specified
2024-09-18T11:40:02.169Z	FATAL	option initialize error: arguments error
Error: Process completed with exit code 1.
```

## minimum project

One dummy module:

```yaml
# modules/project/main.tf
resource "random_string" "random_suffix" {
  length      = 4
  min_numeric = 1
  min_lower   = 1
  special     = false
  upper       = false
}
```

```yaml
# modules/project/outputs.tf
output "random_suffix" {
  value = random_string.random_suffix
}
```

A main.tf which uses the module:

```yaml
# main.tf
module "random_suffix" {
  source = "./modules/project"
}

output "random_suffix" {
  value = module.random_suffix.random_suffix
}
```

## Github Actions Workflow

Using the minimal github workflow:

```yaml
# .github/workflows/pre-commit-trivy.yml
name: pre-commit-trivy

on:
  push:
    branches: [main, feature/*]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: opentofu/setup-opentofu@v1
    - run: | # install trivy
        wget -O /tmp/trivy.tar.gz https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.tar.gz
        tar -xzf /tmp/trivy.tar.gz -C /tmp/
        chmod +x /tmp/trivy
        mv /tmp/trivy /usr/local/bin/trivy
    - uses: pre-commit/action@v3.0.1
```

Push to the `main` or a `feature/something`-branch, and the github action will fail.

### Environment information

Public github runner (config provided above)

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```bash
fail_fast: false
repos:
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v1.0.2
    hooks:
      - id: tofu_trivy
        args:
          - --args=--skip-dirs="**/.terraform"
```

</details>
